project:
  type: website
  output-dir: docs

website:
  title: "Mysite"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - publications.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true


execute:
  freeze: auto
