project:
  type: website
  output-dir: docs

website:
  title: "Tobias Gerken"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - teaching.qmd
      - publications.qmd
      #- about.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true


execute:
  freeze: auto
