# Media Coverage & Outreach

## Air Quality: 
- [Wildfire smoke leaves local impact on health, nature](https://www.dnronline.com/news/wildfire-smoke-leaves-local-impact-on-health-nature/article_a22dace2-8ed1-56f9-bff3-9c069a9f2d10.html); Daily News Record (24 July 2023)

## Climate Outreach 
- Panel Member in Live Podcast and Panel Discussion for combined JMU Wellness Passport and JMU Civic Event, [JMU Democracy Matters - Episode 91: Climate Action Now](https://www.jmu.edu/news/civic/2021/11-03-democracy-matters-episode-91.shtml) (Nov 2021)
- Podcast Guest for Earth Day on [JMU Democracy Matters Podcast: Episode 57: Can we stop climate destruction?](https://www.jmu.edu/news/civic/2021/04-21-democracy-matters-episode-57.shtml) (April 2021)
- Speaker: JMU Climate Strike, Invited by student organizers, [The Breeze Coverage](https://www.breezejmu.org/multimedia/jmu-students-and-harrisonburg-community-members-gather-for-the-harrisonburg-climate-strike/collection_5224428e-3d96-11ed-8607-4bf23a7a251c.html#3) (Sep 26, 2022)
- [JMU joins universities, nonprofits across nation in data rescuing efforts](https://www.breezejmu.org/news/jmu-joins-universities-nonprofits-across-nation-in-data-rescuing-efforts/article_997d0db3-f74c-4897-9e2a-b313e52b4d89.html); The Breeze (3 April 2025)


## Coverage for Artic Research: 
- Press Release: [The Arctic Design Group embrace trial and error during their recent field season in Alaska](./files/UVA_PressRelease_ArcticResearch_2022.pdf), UVA School of Architecture, (10-6-2022)

## Coverage for Atmospheric Carbon and Transport Research:
- Feature: [To the Air for Answers](./files/PSUImpact_AirForAnswers_2022.pdf), Impact Magazine of PennState College of Earth and Mineral Sciences, 2022

## Coverage for Northern Great Plains Research:
- Cover Story: Let it Rain, The Furrow -  A John Deere Publication (Jun 2018) – no longer accessible online
- [How farmers on the Great Plains are changing the local climate](https://massivesci.com/articles/farms-climate-change-crop-rotation-rain-fallow), Massive Science (Apr 2018)
