## Presentations

### Invited Presentations

**Gerken, T**: Lightning Talk, Using Continuous Atmospheric Boundary Layer Observations to constrain carbon dioxide exchange in Amazonia, Workshop on impacts of unusual weather events and climate anomalies on Amazon rainforest, Manaus, Brazil: 20-22 May 2024

**Gerken, T:** Lightning Talk, Madison Celebration of Research and Scholarship, James Madison University, 16 Oct 2023 

**Gerken, T** Davis, KJ & the ACT-America Science Team: Atmospheric Carbon & Transport America - Working to constrain green-house gas fluxes in North America; University of Exeter (UK) – Global Systems Institute Lunchtime Research Talks, Exeter: 18 February 2020

**Gerken, T**: From Draught to Deluge – Land atmosphere coupling and the moistening of the Northern Great Plains (Talk); Clemson University – South Carolina Water Resources Center, Clemson: 6 July 2019 

**Gerken, T**: Moistening trends in the northern North American Great Plains enhance land-atmosphere coupling and convectively primed conditions (Talk); University of Virginia – Atmospheric Seminar, Charlottesville: 10 November 2017

**Gerken, T**: Turbulence meets air chemistry in the Amazon: A modelling study (Talk); Montana State University – Department of Land Resources & Environmental Sciences Seminar, Bozeman: 27 June 2016

**Gerken, T**: Surface-atmosphere interactions: Results from the Green Ocean Amazon (Talk); University of Arizona – Department of Atmospheric Science Seminar, Tucson: 27 April 2016

**Gerken, T**: Turbulence and air chemistry in the Amazon rainforest (Talk); University of Virginia – Department of Environmental Sciences Seminar, Charlottesville: 21 January 2016

**Gerken, T**; Chamecki, M; Fuentes, JD; Katul, GG; Manzi, AO; Nascimento dos Santos, RM; Von Randow, C; Schumacher, C; Stoy, PC; Toledo Machado, LA; Tóta, J; Trowbridge A: Processes influencing rainfall features in the Amazon region (Talk); American Geophysical Union Fall Meeting, San Francisco: 15-19 December 2014 

**Gerken, T**; Herzog, M; Babel, W; Biermann, T; Ma, Y; Graf, HF; Foken, T: Surface-Atmosphere interactions at the Nam Co basin: Current research and perspectives for modelling across scales (Talk); Atmo-Cryo-Hydro: spheres and interactions workshop, Berlin: 11-12 January 2011

**Gerken, T**; Herzog, M; Babel, W; Biermann, T; Ma, Y; Graf, HF; Foken, T: Surface-atmosphere Interactions and Convective Events at Nam Co lake on the Tibetan Plateau (Talk); Tibetan Plateau Research, Atmosphere-ecosystem-glacier cluster Workshop, Göttingen: 11-12 November 2010

### Conference Presentations

**Key:** Presenter = **bold**;  *JMU student = italics*; Mentored Graduate Student = **^**

**Bentley, M**; Sae-jung, J; Duan, Z; Gerken, T: Thermodynamic-Aerosol Relationships of Thunderstorm Environments in the Bangkok Metropolitan Region (Poster), EGU General Assembly 2025, Vienna, Austria, 27 Apr–2 May 2025

**Gerken, T**; Zhong, Y; Otkin, JA; Stoy, PC: Land-Atmosphere Interactions Associated with U.S. Northern and Southern Great Plains Droughts in 2021 and 2022: 39th Conference on Hydrology at the American Meteorological Society Annual Meeting, New Orleans, 12-16 January 2025 

_La Rosa, B_; _**Burris, J.**_; Gerken, T: Understanding potential evapotranspiration dynamics before and during the onset of the 2021 Northern Great Plains and 2022 Southern Great Plains Droughts (Poster): 24th Annual Student Conference at the American Meteorological Society Annual Meeting, New Orleans, 12-16 January 2025 

**Duan, Z**; _Agresto, J_; Bentley, M; Gerken, T.; Dudley, B: Analyzing Ground-lightning Dataset Using the Density Based Spatial Clustering of Applications with Noise (DBSCAN), 2024 IEEE International Performance, Computing, and Communications Conference, Orlando 22-24 November 2024

**Gerken, T**; *Abbot, H; Lang, CA*; Bentley, M; Bonsal, D; Duan, Z; Way H: Validation and Sensitivity Testing of a Lightning Grouping Algorithm on Thunderstorm Climatologies (Poster): 28th Conference on Applied Climatology at the American Meteorological Society Annual Meeting, 28 January – 1 February 2024 [[Available Online](./files/AMS_Poster_Gerken_2024.pdf)]

**^Shaban, M**; Epstein, HE; Murillo, LFR; Gerken, T; Cho, L; Jull, MG; Nelson, M; Wylie, CD; Bradley, H; Nelson, L; Van Metre; E; Fallin, K: Spatiotemporal assessment of ground temperature hot and cold spots at urban sites in Utqiaġvik, Alaska (Poster), American Geophysical Union Fall Meeting, San Francisco: 11-15 December 2023 

**Epstein, HE**; Jull, MG; Cho, L; ^Shaban, M; Griffin, C; Nelson, M; Wylie, CD; Bradley, H; Murillo, LFR;  Gerken, T; Brown, RE; Douglas, T: Sullivan, T; Bosche, L; Nelson, L; Davis, G; Charoonsophonsak, C; Cooke, A: Examining Interactions between the Built and Natural Environments in an Arctic Community: an Utqiaġvik Sensor Array, American Geophysical Union Fall Meeting, San Francisco: 11-15 December 2023

**_Wilczynski, L_**; *Szakal, E*; *Donaldson, JH*; *Pham, M; Abbot HH; Land CA*; Bentley, M; Gerken, T; Duan, Z; Bonsal, D; Way H: Impacts of Urbanization on Climate: A Case Study of the Kansas City Region (Poster); 22nd Annual Student Conference at the American Meteorological Society Annual Meeting, 7-8 January 2023

**Bonsal, D**; Bentley, M; Duan, Z; Gerken, T; Way, H; *Szakal, E*; *Donaldson, H*; *Wilczynski, L*; *Lang, C*; *Abbott, H*; *Pham M*: Analysis of the Climatological Factors that Promote and Inhibit Thunderstorm Activity in the Washington, DC Region (Talk); American Association of Geographers, Annual Meeting, Denver: 20-27 March 2023

***Donaldson, H;*** *Wilczynski, L*; *Szakal, E*; *Pham, M*; *Abbott, H*; *Lang, C*; Bentley, M; Bonsal, D; Gerken, T; Duan, Z; Way, H: Visualizing Urban Thunderstorms: A Data-Mining Approach to Analyzing Relationships with Atmospheric Conditions (Poster); American Association of Geographers, Annual Meeting, Denver: 20-27 March 2023

***Pham, M***; *Szakal, E*; Duan, Z; Bentley, M; Gerken, T; Bonsal D: A Parallel Spatiotemporal Clustering Algorithm with MPI in Analyzing Ground-lightning Dataset (Poster); ACM Capital Region Celebration of Women in Computing Annual Meeting, Richmond, VA: 31 March 2023 

**Gerken, T**; Bentley, M; Bonsal, D; Duan, Z; Way H, *Szakal, E*; *Pham, M*; *Tucker, A; Wilczynski, L*: Impacts of Urbanization on Climate: A Case Study of the Washington D.C. Region (Poster): 11th Conference on the Meteorological Application of Lightning Data at the American Meteorological Society Annual Meeting, 8-12 January 2023

**Gerken, T**; Davis, KJ; Keller, K; Feng, S: Application of PRIM (Patient Rule Induction Method) for understanding patterns in CO2 model-observation differences (Poster); American Geophysical Union Fall Meeting, Chicago: 12-16 December 2022 

**Murillo, FLR**; ^Shaban, M; Readey, J; Gerken, T; Epstein HE: Open Environmental Data Stewardship: Challenges and promises of FAIR-CARE integration for data protection and sharing (Talk); American Geophysical Union Fall Meeting, Chicago: 12-16 December 2022 

**^Shaban, M**; Nelson, M; Cho, L; Charoonsophonsak, C; Davis, G; Douglas, T; Gerken, T; Griffin, CG; Jull, MG; Murillo, FLR; Nelson, L; Wylie, CD; Epstein HE: Assessing Micrometeorological Differences Related to the Built Environment in Utqiagvik, Alaska (Poster); American Geophysical Union Fall Meeting, Chicago: 12-16 December 2022

***Wilczynski, L***; *Szakal, E*; Duan, Z; *Tucker, A*; Bonsal, D; Bentley, M; Gerken, G; *Pham, M*; Way H: Development of a Lightning Grouping Algorithm for Thunderstorm Event Analysis in the Washington D.C. Region (Poster). Southern Appalachian Weather| and Climate Workshop. Asheville, NC: 25-26 March 2022

***Szakal, E***; *Pham, M*; Duan, Z; *Tucker, A; Wilczynski, L*; Bonsal, D; Bentley, M; Gerken, T; Way, H: Development of a lightning flash clustering algorithm to identify thunderstorm events within the Washington, DC metropolitan area (Poster). ACM Capital Region Celebration of Women in Computing Annual Conference. Washington, DC. 25-26 March 2022

**Bonsal, D**; *Tucker, A; Szakal, E; Pham, M;* Duan, Z; *Wilczynski, L*; Bentley, M; Gerken, T; Way, H: Visualization of Lightning for Documenting the Spatiotemporal Patterns of Thunderstorms in Washington, DC. Association of American Geographers Annual Conference (Talk). New York City, NY. 25 Feb – 1 March 2022 

**Vilà-Guerau de Arellano, J,** Pedruzo-Bagazgoitia, X, Moene, AF, Ouwersloot, AF, Machado, LAT, Martin, ST, Patton, EG, Sörgel, M, Stoy, PC, Yamasoe, MA: Investigating the diurnal radiative, turbulent and biophysical processes in the Amazonian canopy-atmosphere interface by combining LES simulations and observations (Talk). European Geosciences Union General Assembly, Vienna Austria, 23–27 May 2022

**Gerken, T**, Helbig, M, Beamesderfer, ER, Baldocchi, DD, Banerjee, T, Biraud, SC, Brown, WOJ, Brunsell, NA, Burakowski, EA, Burns, SP, Butterworth, BJ, Chan, WS, Davis, KJ, Desai, AR, Fuentes, JD, Hollinger, DY, Kljun, N, Mauder, M, Novick, KA, Perkins, JM, Rahn, DA, Rey-Sanchez, C, Santanello, JA, Scott, RL, Seyednasrollah, B, Stoy, PC, Sullivan, RC, Vilà-Guerau de Arellano, J, Wharton, S, Yi, C, Richardson, AD: Integrating continuous atmospheric boundary layer and tower-based flux measurements to advance understanding of land-atmosphere interactions (Talk). American Meteorological Society Annual Meeting, Virtual, 10-15 January 2021

**Beamesderfer, ER**, Helbig, M, Gerken, T, Brunsell, NA, Novick, K; Richardson, AD: Understanding the Role of Energy Fluxes in Shaping the Seasonal Patterns of ABL Heights and Cloud Dynamics for Select AmeriFlux Sites across the United States (Talk) American Meteorological Society Annual Meeting, Virtual, 10-15 January 2021

**Pedruzo-Bagazgoitia, X**, Moene, AF, Ouwersloot, AF, , Machado, LAT, Martin, ST, Patton, EG, Sörgel, M, Stoy, PC, Yamasoe, MA, Vilà-Guerau de Arellano, J: Investigating the diurnal radiative, turbulent and biophysical processes in the Amazonian canopy-atmosphere interface by combining LES simulations and observations (Talk). European Geosciences Union General Assembly, virtual, 19-30 April 2021

**Gerken, T**; Davis, KJ; Feng, S; Keller, K: Comparison of the observed and modeled CO2 mole fractions during ACT-America 2016-2018, (eLightning); American Geophysical Union Fall Meeting, San Francisco: 9-13 December 2019

[ ](https://agu.confex.com/agu/fm19/meetingapp.cgi/Paper/518599)**Gerken, T**; Ruddell, BL; Yu, R; Stoy, PC; Drewry D: Mapping land-atmosphere feedbacks using FLUXNET information flows (Talk); American Geophysical Union Fall Meeting, Washington, DC: 10-14 December 2018

**Gerken, T**; Bromley, GT; Stoy, PC: Investigating land-atmosphere coupling and convective triggering associated with the moistening of the northern North American Great Plains (Talk); American Geophysical Union Fall Meeting, New Orleans: 10-15 December 2017

**Gerken, T**; Bromley, GT; Stoy, PC: Investigating land-atmosphere coupling and convective triggering associated with the moistening of the northern North American Great Plains (Talk); European Geosciences Union General Assembly, Vienna: 23-28 April 2017 

**Gerken, T**; Bromley, GT; Stoy, PC: Investigating land-atmosphere coupling and convective triggering associated with the moistening of the northern North American Great Plains (Talk); American Geophysical Union Fall Meeting, New Orleans: 10-15 December 2017 

**Gerken, T**; Chamecki, M; Fuentes, JD; Stoy, PC; Trowbridge, A; Wei D: Turbulent transport and chemistry of isoprene and monoterpenes within tropical forest canopies and the convective boundary layer (Talk); American Geophysical Union Fall Meeting, San Francisco: 12-16 December 2016 

**Gerken, T**; Chamecki, M; Fuentes, JD; Stoy, PC; Wei D:  Impacts of turbulent transport and chemistry on the oxidation of isoprene and monoterpenes in the tropical convective boundary-layer (Talk); AMS Third Conferences on Atmospheric Biogeosciences, Salt Lake City: 20-24 June 2016

**Gerken, T**; Chamecki, M; Fuentes, JD: Large Eddy Simulation of interaction between BVOC transport and chemistry (Talk); 9th Brazilian Micrometeorology Workshop, Santa Maria: 11-13 November 2014 

**Gerken, T**; Fuentes, JD; Chamecki, M; Katul, GG; Jardine, A; Jardine, K; Manzi, AO; Nacimento dos Santos, RM; Stoy, PC; Trowbridge, A; Von Randow, C: Atmospheric chemistry within and above a forest canopy in the central Amazon (Talk); GoAmazon 2014/5 Science Conference, Harvard University, Cambridge (MA): 18-20 May 2015 

**Gerken, T**; Chamecki, M; Fuentes, JD: Air parcel residence times within tropical forest canopies and implications for air chemistry (Talk); American Geophysical Union Fall Meeting, San Francisco:  15-19 December 2014 

**Gerken, T**; Herzog, M; Babel, W; Biermann, T; Ma, Y; Graf, HF; Foken, T: Surface-atmosphere interactions and convection triggering in the Nam Co Lake basin (Poster); American Geophysical Union Fall Meeting, San Francisco: 9-12 December 2013

**Gerken, T**; Herzog, M; Ma, Y; Foken, T; Graf, HF: [High resolution atmospheric modelling on the Tibetan Plateau: How to understand a system with sparse observations? (Short Talk and Poster)](http://www.bayceer.uni-bayreuth.de/mm/de/pub/vp/detail.php?id_obj=118036); Interdisciplinary Conference of Young Earth System Scientists, Hamburg: 22-25 September 2013

**Gerken, T**; Babel, W; Biermann, T; Hoffmann, A; Herzog, M; Ma, Y; Foken, T; Graf, HF: Surface-atmosphere interactions: Mesoscale circulations at Nam Co lake (Poster), 7th Sino-German Workshop on Tibetan Plateau Research, Hamburg: 3-8 April 2011

**Gerken, T**; Herzog, M; Babel, W; Biermann, T; Ma, Y; Graf, HF; Foken, T: Investigation of surface-atmosphere interactions and convective events at Nam Co Lake (Talk); 2nd CAS-CEOP Workshop, Lhasa: 19-21 July 2010

**Gerken, T**; Herzog, M; Babel, W; Biermann, T; Ma, Y; Graf, HF; Foken, T: Investigation of surface-atmosphere interactions and convective events at Nam Co Lake (Talk); Royal Meteorological Society Student Conference, Exeter: 8-10 July 2010

**Gerken, T**; Serafimovich, A; Foken, T: Multilevel Investigation of Subcanopy Respiration Flux by Relaxed Eddy Accumulation Conditional Sampling above and within a Spruce Forest (Talk); EGU General Assembly 2009, Vienna: 19-24 April 2009

**Gerken, T**; Babel, W; Biermann, T; Hoffmann, A; Herzog, M; Ma, Y; Foken, T; Graf, HF Modeling Surface-Atmosphere Interactions: A simple, coupled surface model applied at Nam Co Lake (Poster); International Workshop on Land Atmosphere Interactions at the regional scale, Madrid: 08-10 October 2012

**Gerken, T**; Babel, W; Biermann, T; Hoffmann, A; Herzog, M; Ma, Y; Foken, T; Graf, HF: Surface-Atmosphere Interactions: Boundary Layer Clouds and Mesoscale Circulations at Nam Co Lake (Poster); 3rd iLEAPS Science Conference, Garmisch-Partenkirchen: 18-23 September 2011

Biermann, T; Babel, W; **Gerken, T** (presenter); Chen, X; Ma, W, Ma, Y; Graf, HF; Foken, T: Surface-atmosphere exchange measurements over lake and grassland at Nam Tso, 2009 (Talk); 6th Sino-German Workshop on Tibetan Plateau Research, Qingdao: 8-12 October 2009

**Gerken, T**; Herzog, M; Foken, T; Graf, HF: Surface-Atmosphere interactions at lake Nam Co: The importance of surface fluxes (Poster); 6th Sino-German Workshop on Tibetan Plateau Research, Qingdao: 8-12 October 2009

**Gerken, T**; Serafimovich, A; Foken, T: Multilevel investigation of subcanopy respiration flux by Relaxed Eddy Accumulation Conditional Sampling (Poster); Atmospheric Transport and Chemistry in Forest Ecosystems, Thurnau: 5-10 October 2009

**Gerken, T**; Babel, W; Biermann, T; Hoffmann, A; Herzog, M; Ma, Y; Foken, T; Graf, HF: Surface-Atmosphere interactions: Modelling the development of local circulations and generation of convection at Nam Co Lake (Poster); EGU General Assembly 2011, Vienna: 03-08 April 2011

**Gerken, T**; Foken, T; Graf, HF: Land use, convection and the water cycle: The Tibetan Plateau example (Poster); The Global Water Initiative Implications of Climate Change and Variability on African Water Resources, Cambridge: 21-23 September 2009

**Gerken, T**; Serafimovich, A; Foken, T: Multilevel investigation of subcanopy respiration flux by Relaxed Eddy Accumulation Conditional Sampling (Talk); EGU General Assembly 2009, Vienna:19-24 April 2009